// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// numeric_limits_min_float
float numeric_limits_min_float();
RcppExport SEXP clairvoyant_numeric_limits_min_float() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(numeric_limits_min_float());
    return __result;
END_RCPP
}
// numeric_limits_max_float
float numeric_limits_max_float();
RcppExport SEXP clairvoyant_numeric_limits_max_float() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(numeric_limits_max_float());
    return __result;
END_RCPP
}
