# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Numeric limit of a min float
#'
#' @export
numeric_limits_min_float <- function() {
    .Call('clairvoyant_numeric_limits_min_float', PACKAGE = 'clairvoyant')
}

#' Numeric limit of a max float
#'
#' @export
numeric_limits_max_float <- function() {
    .Call('clairvoyant_numeric_limits_max_float', PACKAGE = 'clairvoyant')
}

